"""auto_migration_20250321_082433

Revision ID: bd5ea5a256d8
Revises: 186c8f37eddd
Create Date: 2025-03-21 08:24:35.100738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5ea5a256d8'
down_revision: Union[str, None] = '186c8f37eddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
