from app.schemas.common import *
from app.schemas.user import *
from app.schemas.major import *
from app.schemas.academic_year import *
from app.schemas.subject import *
from app.schemas.tag import *
from app.schemas.document import *
from app.schemas.comment import *
from app.schemas.rating import *
from app.schemas.forum import *
from app.schemas.notification import *
from app.schemas.system_config import *
from app.schemas.document_history import *
from app.schemas.shared_link import *
from app.schemas.department import *