from app.api.v1.endpoints import auth
from app.api.v1.endpoints import users
from app.api.v1.endpoints import academic_year
from app.api.v1.endpoints import major
from app.api.v1.endpoints import documents
from app.api.v1.endpoints import tag
from app.api.v1.endpoints import document_tag
from app.api.v1.endpoints import subjects
from app.api.v1.endpoints import comments
from app.api.v1.endpoints import ratings
from app.api.v1.endpoints import document_history